GET http://localhost:8000
###
GET http://localhost:8000/api/jogallasok
###
GET http://localhost:8000/api/megyek
###
GET http://localhost:8000/api/telepulesek
###
GET http://localhost:8000/api/jogallasok/jogallas/város
###
GET http://localhost:8000/api/megyek/megye/békés
###
GET http://localhost:8000/api/telepulesek/telepulesnev/csorvás
